[package]
name = "recommendation-system"
version = "0.1.0"
authors = [ "Kevin Del Castillo <quebin31@gmail.com>" ]
edition = "2018"

[workspace]
members = [
    "controller",
    "controllers/*",
    "recommend",
]

[dependencies]
anyhow = "1"
controller = { version = "*", path = "controller" }
books = { version = "*", path = "controllers/books" }
movie-lens-small = { version = "*", path = "controllers/movie-lens-small" }
simple-movie = { version = "*", path = "controllers/simple-movie" }
text_io = "0.1"
recommend = { version = "*", path = "recommend" }