[system]
# Verbose levels:
#   0  => Errors (log::error!)
#   1  => Warnings (log::warning!)
#   2  => Info (log::info!)
#   3+ => Debug (log::debug!)
file_verbosity_level = 2
log_output = "rsys.log"
term_verbosity_level = 0

[matrix]
allow_chunk_optimization = true 
chunk_size_threshold = 0.3 # percentage of original size
partial_users_chunk_size = 10000 

[engine]
partial_users_chunk_size = 10000

[databases.simple-movie]
mongo_db = "simple-movie"
mongo_url = "mongodb://localhost:27017"
psql_url = "postgres://postgres:@localhost/simple-movie"
use_postgres = false

[databases.books]
mongo_db = "books"
mongo_url = "mongodb://localhost:27017"
psql_url = "postgres://postgres:@localhost/books"
use_postgres = false

[databases.shelves]
mongo_db = "shelves"
mongo_url = "mongodb://localhost:27017"
psql_url = "postgres://postgres:@localhost/shelves"
use_postgres = false

[databases.movie-lens]
mongo_db = "movie-lens"
mongo_url = "mongodb://localhost:27017"
psql_url = "postgres://postgres:@localhost/movie-lens"
use_postgres = false

[databases.movie-lens-small]
mongo_db = "movie-lens-small"
mongo_url = "mongodb://localhost:27017"
psql_url = "postgres://postgres:@localhost/movie-lens-small"
use_postgres = false
