[system]
file_verbosity_level = 2
log_output = "rs.log"
term_verbosity_level = 1

[matrix]
allow_chunk_optimization = true
chunk_size_threshold = 0.3
partial_users_chunk_size = 10000

[engine]
partial_users_chunk_size = 10000

[databases.some-database]
mongo_db = "some-database"
mongo_url = "mongodb://localhost:27017"
psql_url = "postgres://postgres:@localhost/some-database"
users_ratings_mongo = false
users_who_rated_mongo = true
